import type { Metadata } from 'next'
import './globals.css'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <ClerkProvider>
      <html lang="ja">
        <body cz-shortcut-listen="true" className="antialiased">
          <header className="fixed top-0 left-0 w-full z-50 h-18 bg-gray-700 flex items-center justify-end">
            <SignedOut>
              <div className="h-fit mr-16 bg-green-400 w-fit p-2 rounded-md text-gray-600 text-sm font-semibold">
                <SignInButton />
              </div>
            </SignedOut>
            <SignedIn>
              <div className="h-fit ml-4 w-fit">
                <UserButton />
              </div>
            </SignedIn>
          </header>
          <main className="min-h-[calc(100dvh-4rem)] max-w-full pt-16">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}

export default RootLayout